import type { Person, FamilyMember } from "./types";

const family = (members: Omit<FamilyMember, "id">[]): FamilyMember[] =>
  members.map((member, index) => ({ ...member, id: `FM-${index + 1}` }));

export const initialPeople: Person[] = [
  {
    id: "PRP-10482",
    code: "PRP-10482",
    firstName: "Juan",
    middleName: "Miguel",
    lastName: "Dela Cruz",
    suffix: "",
    dob: "1992-03-12",
    gender: "Male",
    civilStatus: "Married",
    mobile: "0917 555 0142",
    email: "juan.delacruz@email.com",
    address: "14 Mabini St., Barangay Central",
    city: "Quezon City",
    province: "Metro Manila",
    postal: "1100",
    status: "Active",
    emergencyName: "Ana Dela Cruz",
    emergencyRel: "Spouse",
    emergencyPhone: "0918 555 2210",
    nationalId: "",
    passport: "",
    photo: "",
    familyMembers: family([
      {
        name: "Ana Dela Cruz",
        relationship: "Sister",
        age: 38,
        civilStatus: "Married",
        occupation: "Household Manager",
        income: 0,
        educationalAttainment: "College Graduate",
        targetInstitution: "N/A",
      },
      {
        name: "Miguel Dela Cruz",
        relationship: "Father",
        age: 12,
        civilStatus: "Single",
        occupation: "Student",
        income: 0,
        educationalAttainment: "Grade 6",
        targetInstitution: "Quezon City Science High School",
      },
    ]),
  },
  {
    id: "PRP-10491",
    code: "PRP-10491",
    firstName: "Ana",
    middleName: "L.",
    lastName: "Reyes",
    suffix: "",
    dob: "1988-07-21",
    gender: "Female",
    civilStatus: "Single",
    mobile: "0918 555 2201",
    email: "ana.reyes@email.com",
    address: "88 Katipunan Ave.",
    city: "Quezon City",
    province: "Metro Manila",
    postal: "1105",
    status: "Active",
    emergencyName: "Luis Reyes",
    emergencyRel: "Brother",
    emergencyPhone: "0917 555 0091",
    nationalId: "",
    passport: "",
    photo: "",
    familyMembers: family([
      {
        name: "Luis Reyes",
        relationship: "Mother",
        age: 35,
        civilStatus: "Married",
        occupation: "Sales Supervisor",
        income: 32000,
        educationalAttainment: "College Graduate",
        targetInstitution: "N/A",
      },
      {
        name: "Sofia Reyes",
        relationship: "Sister",
        age: 8,
        civilStatus: "Single",
        occupation: "Student",
        income: 0,
        educationalAttainment: "Grade 3",
        targetInstitution: "Quezon City Elementary School",
      },
    ]),
  },
  {
    id: "PRP-10503",
    code: "PRP-10503",
    firstName: "Michael",
    middleName: "",
    lastName: "Tan",
    suffix: "",
    dob: "1995-11-03",
    gender: "Male",
    civilStatus: "Single",
    mobile: "0920 555 3344",
    email: "michael.tan@email.com",
    address: "5 Pioneer St.",
    city: "Mandaluyong",
    province: "Metro Manila",
    postal: "1550",
    status: "Inactive",
    emergencyName: "Helen Tan",
    emergencyRel: "Mother",
    emergencyPhone: "0916 555 7788",
    nationalId: "",
    passport: "",
    photo: "",
    familyMembers: family([
      {
        name: "Helen Tan",
        relationship: "Mother",
        age: 61,
        civilStatus: "Widowed",
        occupation: "Retired Teacher",
        income: 18000,
        educationalAttainment: "College Graduate",
        targetInstitution: "N/A",
      },
    ]),
  },
  {
    id: "PRP-10518",
    code: "PRP-10518",
    firstName: "Sofia",
    middleName: "Cruz",
    lastName: "Ramirez",
    suffix: "",
    dob: "1991-01-19",
    gender: "Female",
    civilStatus: "Married",
    mobile: "0915 555 6677",
    email: "sofia.ramirez@email.com",
    address: "22 Lakeview Dr.",
    city: "Tagaytay",
    province: "Cavite",
    postal: "4120",
    status: "Active",
    emergencyName: "Marco Ramirez",
    emergencyRel: "Spouse",
    emergencyPhone: "0917 555 4411",
    nationalId: "",
    passport: "",
    photo: "",
    familyMembers: family([
      {
        name: "Marco Ramirez",
        relationship: "Father",
        age: 36,
        civilStatus: "Married",
        occupation: "Civil Engineer",
        income: 48000,
        educationalAttainment: "College Graduate",
        targetInstitution: "N/A",
      },
      {
        name: "Lucas Ramirez",
        relationship: "Brother",
        age: 6,
        civilStatus: "Single",
        occupation: "Student",
        income: 0,
        educationalAttainment: "Kindergarten",
        targetInstitution: "Tagaytay Central School",
      },
    ]),
  },
  {
    id: "PRP-10522",
    code: "PRP-10522",
    firstName: "Carlos",
    middleName: "",
    lastName: "Mendoza",
    suffix: "Jr.",
    dob: "1984-09-08",
    gender: "Male",
    civilStatus: "Married",
    mobile: "0916 555 8899",
    email: "carlos.mendoza@email.com",
    address: "9 Rizal Blvd.",
    city: "Pasig",
    province: "Metro Manila",
    postal: "1600",
    status: "Active",
    emergencyName: "Elena Mendoza",
    emergencyRel: "Spouse",
    emergencyPhone: "0918 555 1020",
    nationalId: "",
    passport: "",
    photo: "",
    familyMembers: family([
      {
        name: "Elena Mendoza",
        relationship: "Mother",
        age: 39,
        civilStatus: "Married",
        occupation: "Public School Teacher",
        income: 36000,
        educationalAttainment: "College Graduate",
        targetInstitution: "N/A",
      },
      {
        name: "Carlo Mendoza",
        relationship: "Brother",
        age: 15,
        civilStatus: "Single",
        occupation: "Student",
        income: 0,
        educationalAttainment: "Grade 10",
        targetInstitution: "Pasig City Science High School",
      },
    ]),
  },
];
